language: node_js
sudo: true
node_js: stable
script:
- npm run codecov
env:
  global:
  - CF_APP=text-to-speech-demo
  - CF_API=https://api.ng.bluemix.net
  - CF_ORGANIZATION=WatsonPlatformServices
  - CF_SPACE=demos
before_deploy: npm install -g cf-blue-green
deploy:
  provider: script
  script:
    - cf-blue-green-travis
  on:
    branch: master
    repo: watson-developer-cloud/text-to-speech-nodejs
  skip_cleanup: true
  provider: script
  script:
    - CF_APP=text-to-speech-react cf-blue-green-travis
  on:
    branch: react-jbs
    repo: watson-developer-cloud/text-to-speech-nodejs
  skip_cleanup: true

notifications:
  email: false
